version: 2
project_name: git-swap

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # Use standard naming conventions
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  - name: git-swap
    repository:
      owner: jokot
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/jokot/git-swap"
    description: "Quickly switch between multiple git accounts across multiple hubs."
    license: "MIT"
    test: |
      system "#{bin}/git-swap --help"

winget:
  - name: git-swap
    publisher: jokot
    author: jokot
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Winget update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Quickly switch between multiple git accounts across multiple hubs."
    license: "MIT"
    homepage: "https://github.com/jokot/git-swap"
    repository:
      owner: jokot
      name: winget-pkgs
      branch: "{{ .ProjectName }}-{{ .Version }}"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
    path: manifests/j/jokot/git-swap/
    skip_upload: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
